name: iOS build test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Generate xcconfig
        run: |
          mkdir -p ByeBoo-iOS/Data/Config
          echo "BASE_URL = ${BASE_URL}" > ByeBoo-iOS/Data/Config/Config.xcconfig
        env:
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Build with xcodebuild
        run: |
          # 사용 가능한 iPhone 시뮬레이터 선택
          DEVICE=$(xcrun simctl list devices available | grep "iPhone 15" | head -n 1 | awk -F '(' '{print $1}' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          echo "Using simulator: $DEVICE"

          # 해당 기기에 사용 가능한 iOS 버전들 중에서 선택
          DEVICE_WITH_OS=$(xcrun simctl list devices available | grep "$DEVICE" | head -n 1)
          AVAILABLE_OS=$(echo "$DEVICE_WITH_OS" | sed 's/.*iOS \([0-9.]*\).*/\1/')
          
          echo "Device with OS info: $DEVICE_WITH_OS"
          echo "Extracted iOS version: $AVAILABLE_OS"
          
          set -o pipefail
          xcodebuild \
            -project ByeBoo-iOS/ByeBoo-iOS.xcodeproj \
            -scheme ByeBoo-iOS \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=${DEVICE}, OS=${AVAILABLE_OS}" \
            clean build | xcpretty

