name: Fastlane CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
    types: [closed]

jobs:
  fastlane:
    name: Run Fastlane
    runs-on: macos-latest
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    defaults:
      run:
        working-directory: ./ByeBoo-iOS
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 

    - name: Install Bundler
      run: gem install bundler

    - name: Install dependencies
      run: bundle install

    - name: Output Fastlane environment
      run: bundle exec fastlane env

    - name: Run upload_testflight
      if: github.event.pull_request.base.ref == 'develop'
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        PRIVATE_REPOSITORY: ${{ secrets.PRIVATE_REPOSITORY }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
      run: bundle exec fastlane upload_testflight

    - name: Run release_app_store on main
      if: github.event_name == 'push' || github.event.pull_request.base.ref == 'main'
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        PRIVATE_REPOSITORY: ${{ secrets.PRIVATE_REPOSITORY }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        DISCORD_URL: ${{ secrets.DISCORD_URL }}
      run: bundle exec fastlane release_app_store
